"""
Data schemas for the forging intelligent maintenance multi-agent framework.
The project intentionally uses only Python standard-library dataclasses so that
it can run in a clean Windows/conda environment without extra dependencies.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field, is_dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import json


JsonDict = Dict[str, Any]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass
class MaintenanceScenario:
    """Structured maintenance scenario S_t generated by scenario awareness."""

    scenario_id: str
    timestamp: str
    equipment_id: str
    equipment_type: str
    task_type: str
    process_stage: str
    operating_condition: JsonDict
    data_modalities: List[str]
    data_quality_score: float
    label_status: str
    unknown_fault_risk: float
    real_time_requirement: str
    risk_level: str
    available_signal_path: Optional[str] = None
    constraints: JsonDict = field(default_factory=dict)
    notes: List[str] = field(default_factory=list)


@dataclass
class PHMModelProfile:
    """Algorithm profile used by the model orchestration agent."""

    model_id: str
    name: str
    version: str
    supported_tasks: List[str]
    supported_modalities: List[str]
    label_settings: List[str]
    applicable_conditions: JsonDict
    strengths: List[str]
    weaknesses: List[str]
    latency_ms: int
    reliability_score: float
    supports_unknown_detection: bool
    supports_online_update: bool
    evidence_tags: List[str] = field(default_factory=list)
    usage_count: int = 0
    recent_error_count: int = 0


@dataclass
class ModelCallPlan:
    """Plan generated by the orchestration agent."""

    selected_model_ids: List[str]
    strategy: str
    reasons: List[str]
    require_human_review: bool
    require_digital_twin_validation: bool


@dataclass
class SignalSummary:
    """Basic signal statistics consumed by demo PHM models and explanations."""

    n: int
    mean: float
    std: float
    rms: float
    peak: float
    crest_factor: float
    kurtosis_like: float
    missing_ratio: float


@dataclass
class ModelOutput:
    model_id: str
    model_name: str
    version: str
    fault_label: str
    health_score: float
    confidence: float
    unknown_score: float
    latency_ms: int
    evidence: JsonDict
    warnings: List[str] = field(default_factory=list)


@dataclass
class KnowledgeEvidence:
    source_id: str
    title: str
    source_type: str
    relevance_score: float
    matched_terms: List[str]
    content: str
    recommended_actions: List[str] = field(default_factory=list)
    safety_notes: List[str] = field(default_factory=list)


@dataclass
class FusionResult:
    final_label: str
    health_score: float
    confidence: float
    uncertainty: float
    explanation: str
    conflicts: List[str]
    model_outputs: List[ModelOutput]
    knowledge_evidence: List[KnowledgeEvidence]
    recommended_actions: List[str]
    require_human_review: bool


@dataclass
class ValidationReport:
    passed: bool
    risk_level: str
    conflicts: List[str]
    violated_rules: List[str]
    suggestions: List[str]
    require_human_review: bool


@dataclass
class MaintenanceDecision:
    decision_id: str
    scenario: MaintenanceScenario
    plan: ModelCallPlan
    fusion: FusionResult
    validation: ValidationReport
    final_actions: List[str]
    evidence_chain: JsonDict
    created_at: str = field(default_factory=utc_now_iso)


@dataclass
class FeedbackRecord:
    decision_id: str
    timestamp: str
    operator_feedback: str
    actual_fault_label: Optional[str]
    maintenance_result: Optional[str]
    followup_health_status: Optional[str]
    notes: List[str] = field(default_factory=list)


class DataclassJSONEncoder(json.JSONEncoder):
    def default(self, obj: Any) -> Any:
        if is_dataclass(obj):
            return asdict(obj)
        return super().default(obj)


def to_pretty_json(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, indent=2, cls=DataclassJSONEncoder)
